(()=>{
  const qs=new URLSearchParams(location.search);if(qs.get('cliente')==='1'||window.__creditiShareV28)return;window.__creditiShareV28=true;
  const API='https://jfguumxlxmveuszddyky.supabase.co',KEY='sb_publishable_F84YmaFbhJGUmNXYrye1Rw_h6xKvW3B',MAX=5,BASE='https://catalogo.creditisolucoes.com.br';
  let modal=null,state=null,busy=false;
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
  const nome=v=>[v?.marca,v?.modelo].filter(Boolean).join(' ').trim()||'Veículo Crediti';
  const tipo=v=>String(v?.categoria||'').toLowerCase().includes('moto')?'moto':String(v?.categoria||'').toLowerCase().includes('carro')?'carro':'veiculo';
  const url=v=>`${BASE}/${tipo(v)}/${encodeURIComponent(v.id)}`;
  function texto(v){const l=['🚘 *OPORTUNIDADE CREDITI*','',`*${nome(v)}*`];if(v.versao&&v.versao!==v.modelo)l.push(`Versão: ${v.versao}`);if(v.ano_fabricacao||v.ano_modelo)l.push(`Ano: ${v.ano_fabricacao||'—'}/${v.ano_modelo||'—'}`);if(+v.quilometragem>0)l.push(`KM: ${Number(v.quilometragem).toLocaleString('pt-BR')} km`);if(+v.nosso_valor>0)l.push('',`💰 *PREÇO CREDITI: ${money(v.nosso_valor)}*`);if(v.descricao)l.push('',`✅ ${v.descricao}`);l.push('','📲 Gostou? Fale com a Crediti para confirmar a disponibilidade e fazer sua simulação.','',`🔗 ${url(v)}`);return l.join('\n')}
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function ensure(){if(modal)return modal;modal=document.createElement('div');modal.id='crediti-share-v28';modal.style.cssText='position:fixed;inset:0;z-index:260;background:rgba(0,0,0,.62);display:none;align-items:flex-end;justify-content:center;font-family:Inter,system-ui,sans-serif';document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal)fechar()});return modal}
  function fechar(){busy=false;state=null;if(modal){modal.style.display='none';modal.replaceChildren()}document.body.style.removeProperty('overflow')}
  function render(){if(!state)return;const r=ensure();r.style.display='flex';document.body.style.setProperty('overflow','hidden','important');const fotos=state.fotos||[];r.innerHTML=`<div style="width:100%;max-width:620px;max-height:92dvh;overflow:auto;background:#fff;border-radius:26px 26px 0 0;padding:18px"><div style="display:flex;justify-content:space-between;gap:12px"><div><div style="font-size:11px;font-weight:900;color:#777;letter-spacing:.1em">COMPARTILHAR VEÍCULO</div><div style="font-size:20px;font-weight:900;margin-top:4px">${esc(nome(state.v))}</div></div><button id="cs-close" style="width:42px;height:42px;border:0;border-radius:13px;background:#f1f1ed;font-size:24px">×</button></div><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:14px">${fotos.map((f,i)=>`<button data-i="${i}" style="position:relative;height:125px;border:${f.on?'3px solid #FDCA01':'1px solid #ddd'};border-radius:14px;padding:3px;background:#fff;opacity:${f.on?1:.5}"><img src="${esc(f.url)}" style="width:100%;height:100%;object-fit:contain;border-radius:10px"><span style="position:absolute;left:7px;bottom:7px;background:${f.on?'#FDCA01':'#111'};color:${f.on?'#111':'#fff'};padding:5px 7px;border-radius:99px;font-size:9px;font-weight:900">${f.on?'ENVIAR':'NÃO ENVIAR'}</span></button>`).join('')}</div><div style="margin-top:12px;padding:12px;background:#f6f6f2;border-radius:14px;font-size:12px;line-height:1.45;white-space:pre-line">${esc(texto(state.v))}</div>${state.erro?`<div style="margin-top:9px;color:#a11212;font-size:12px;font-weight:800">${esc(state.erro)}</div>`:''}<button id="cs-share" ${busy?'disabled':''} style="width:100%;height:52px;margin-top:12px;border:0;border-radius:16px;background:#FDCA01;font-weight:900;opacity:${busy?.55:1}">${busy?'PREPARANDO…':'↗ COMPARTILHAR FOTOS + DADOS'}</button><button id="cs-copy" style="width:100%;height:46px;margin-top:8px;border:1px solid #ddd;border-radius:15px;background:#fff;font-weight:850">COPIAR MENSAGEM + LINK</button><div style="font-size:10px;color:#777;text-align:center;margin-top:8px;line-height:1.35">WhatsApp, Instagram e outros apps podem tratar fotos e texto de formas diferentes. A mensagem fica pronta para copiar quando o app não aceitar tudo junto.</div></div>`;
    r.querySelector('#cs-close').onclick=fechar;r.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{state.fotos[+b.dataset.i].on=!state.fotos[+b.dataset.i].on;render()});r.querySelector('#cs-copy').onclick=copiar;r.querySelector('#cs-share').onclick=compartilhar;
  }
  async function copiar(){try{await navigator.clipboard.writeText(texto(state.v));state.erro='Mensagem e link profissional copiados.'}catch(_){state.erro='Não foi possível copiar automaticamente.'}render()}
  async function buscar(id){const p=new URLSearchParams({id:`eq.${id}`,select:'id,categoria,marca,modelo,versao,ano_fabricacao,ano_modelo,nosso_valor,quilometragem,descricao,fotos_veiculo(id,url_foto,ordem)'});const r=await fetch(`${API}/rest/v1/veiculos?${p}`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`},cache:'no-store'});if(!r.ok)throw 0;const d=await r.json();if(!d?.[0])throw 0;return d[0]}
  async function abrir(id){state={v:{id,modelo:'Veículo'},fotos:[],erro:'Carregando…'};render();try{const v=await buscar(id);const fs=[...(v.fotos_veiculo||[])].sort((a,b)=>(a.ordem||99)-(b.ordem||99)).slice(0,MAX).map(x=>({url:x.url_foto,on:true}));state={v,fotos:fs,erro:fs.length?'':'Este veículo ainda não possui fotos.'};render()}catch(_){state.erro='Não foi possível carregar o veículo. Tente novamente.';render()}}
  async function arquivo(src,i){const r=await fetch(`/api/share-image?src=${encodeURIComponent(src)}`,{cache:'force-cache'});if(!r.ok)throw 0;const b=await r.blob();return new File([b],`crediti-${String(i+1).padStart(2,'0')}.jpg`,{type:b.type?.startsWith('image/')?b.type:'image/jpeg'})}
  async function compartilhar(){if(busy)return;const sel=state.fotos.filter(x=>x.on);if(!sel.length){state.erro='Selecione pelo menos uma foto.';render();return}busy=true;state.erro='';render();try{const files=await Promise.all(sel.map((x,i)=>arquivo(x.url,i)));const dados={title:nome(state.v),text:texto(state.v),url:url(state.v),files};if(!navigator.share)throw new Error('share');if(navigator.canShare&&!navigator.canShare({files}))throw new Error('files');await navigator.share(dados);fechar()}catch(e){if(e?.name==='AbortError'){busy=false;render();return}busy=false;state.erro='O aplicativo escolhido não aceitou fotos e texto juntos. Use “COPIAR MENSAGEM + LINK” e compartilhe as fotos por este botão.';render()}}
  document.addEventListener('click',e=>{const b=e.target.closest?.('button');if(!b||!b.textContent?.includes('Compartilhar com cliente'))return;const a=b.closest('article[id^="veiculo-"]');if(!a)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();abrir(a.id.replace('veiculo-',''))},true);
})();