(()=>{
 const qs=new URLSearchParams(location.search);if(qs.get('cliente')==='1'||window.__creditiShareV31)return;window.__creditiShareV31=true;
 const API='https://jfguumxlxmveuszddyky.supabase.co',KEY='sb_publishable_F84YmaFbhJGUmNXYrye1Rw_h6xKvW3B',MAX=5,BASE='https://catalogo.creditisolucoes.com.br';let modal=null,state=null,busy=false;
 const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0)),nome=v=>[v?.marca,v?.modelo].filter(Boolean).join(' ').trim()||'Veículo Crediti',tipo=v=>String(v?.categoria||'').toLowerCase().includes('moto')?'moto':String(v?.categoria||'').toLowerCase().includes('carro')?'carro':'veiculo',url=v=>`${BASE}/${tipo(v)}/${encodeURIComponent(v.id)}`;
 function texto(v){const l=['🚘 OPORTUNIDADE CREDITI','',nome(v)];if(v.versao&&v.versao!==v.modelo)l.push(`Versão: ${v.versao}`);if(v.ano_fabricacao||v.ano_modelo)l.push(`Ano: ${v.ano_fabricacao||'—'}/${v.ano_modelo||'—'}`);if(+v.quilometragem>0)l.push(`KM: ${Number(v.quilometragem).toLocaleString('pt-BR')} km`);if(+v.nosso_valor>0)l.push('',`PREÇO CREDITI: ${money(v.nosso_valor)}`);if(v.descricao)l.push('',v.descricao);l.push('','Gostou? Fale com a Crediti para confirmar a disponibilidade e fazer sua simulação.','',url(v));return l.join('\n')}
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 function ensure(){if(modal)return modal;modal=document.createElement('div');modal.id='crediti-share-v31';modal.style.cssText='position:fixed;inset:0;z-index:260;background:rgba(0,0,0,.62);display:none;align-items:flex-end;justify-content:center;font-family:Inter,system-ui,sans-serif;overscroll-behavior:contain';document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal)fechar()});return modal}
 function lock(on){document.documentElement.classList.toggle('crediti-share-open',on);document.body.classList.toggle('crediti-share-open',on);if(!document.getElementById('crediti-share-lock')){const s=document.createElement('style');s.id='crediti-share-lock';s.textContent='html.crediti-share-open,body.crediti-share-open{overflow:hidden!important;overscroll-behavior:none!important}';document.head.appendChild(s)}}
 function fechar(){busy=false;state=null;if(modal){modal.style.display='none';modal.replaceChildren()}lock(false)}
 function render(){if(!state)return;const r=ensure();r.style.display='flex';lock(true);const fs=state.fotos||[],btn='height:48px;border:0;border-radius:15px;font-weight:900;font-size:12px;touch-action:manipulation';r.innerHTML=`<div style="width:100%;max-width:620px;max-height:92dvh;overflow:auto;-webkit-overflow-scrolling:touch;background:#fff;border-radius:26px 26px 0 0;padding:18px"><div style="display:flex;justify-content:space-between;gap:12px"><div><div style="font-size:11px;font-weight:900;color:#777;letter-spacing:.1em">COMPARTILHAR VEÍCULO</div><div style="font-size:20px;font-weight:900;margin-top:4px">${esc(nome(state.v))}</div></div><button id="cs-close" style="width:42px;height:42px;border:0;border-radius:13px;background:#f1f1ed;font-size:24px">×</button></div><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:14px">${fs.map((f,i)=>`<button data-i="${i}" style="position:relative;height:120px;border:${f.on?'3px solid #FDCA01':'1px solid #ddd'};border-radius:14px;padding:3px;background:#fff;opacity:${f.on?1:.5}"><img src="${esc(f.url)}" style="width:100%;height:100%;object-fit:contain;border-radius:10px;pointer-events:none"><span style="position:absolute;left:7px;bottom:7px;background:${f.on?'#FDCA01':'#111'};color:${f.on?'#111':'#fff'};padding:5px 7px;border-radius:99px;font-size:9px;font-weight:900">${f.on?'ENVIAR':'NÃO ENVIAR'}</span></button>`).join('')}</div><div style="margin-top:14px;font-size:12px;font-weight:900">ESCOLHA ONDE COMPARTILHAR</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px"><button data-dest="whatsapp" style="${btn};background:#f2f2ed">WhatsApp</button><button data-dest="post" style="${btn};background:#f2f2ed">Instagram Post</button><button data-dest="stories" style="${btn};background:#f2f2ed">Instagram Stories</button><button data-dest="direct" style="${btn};background:#f2f2ed">Instagram Direct</button></div><button data-dest="mais" style="${btn};width:100%;margin-top:8px;background:#FDCA01">MAIS OPÇÕES</button><button id="cs-copy" style="${btn};width:100%;margin-top:8px;background:#fff;border:1px solid #ddd">COPIAR MENSAGEM + LINK</button>${state.erro?`<div style="margin-top:10px;padding:10px;background:#f7f7f3;border-radius:12px;font-size:11px;font-weight:800;color:#555">${esc(state.erro)}</div>`:''}<div style="font-size:10px;color:#777;text-align:center;margin-top:9px;line-height:1.35">Instagram Post, Stories e Direct enviam somente as fotos para aumentar a compatibilidade com o Instagram. No Direct, use “Copiar mensagem + link” e envie o texto logo depois das fotos.</div></div>`;r.querySelector('#cs-close').onclick=fechar;r.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{state.fotos[+b.dataset.i].on=!state.fotos[+b.dataset.i].on;render();prepararArquivos()});r.querySelectorAll('[data-dest]').forEach(b=>b.onclick=()=>compartilhar(b.dataset.dest));r.querySelector('#cs-copy').onclick=()=>copiar(true)}
 async function copiar(aviso=false){try{await navigator.clipboard.writeText(texto(state.v));if(aviso){state.erro='Mensagem e link profissional copiados. Agora é só colar no Direct ou na legenda.';render()}return true}catch(_){if(aviso){state.erro='Não foi possível copiar automaticamente.';render()}return false}}
 async function buscar(id){const p=new URLSearchParams({id:`eq.${id}`,select:'id,categoria,marca,modelo,versao,ano_fabricacao,ano_modelo,nosso_valor,quilometragem,descricao,fotos_veiculo(id,url_foto,ordem)'}),r=await fetch(`${API}/rest/v1/veiculos?${p}`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`},cache:'no-store'});if(!r.ok)throw 0;const d=await r.json();if(!d?.[0])throw 0;return d[0]}
 async function arquivo(src,i){const r=await fetch(`/api/share-image?src=${encodeURIComponent(src)}`,{cache:'force-cache'});if(!r.ok)throw 0;const b=await r.blob();return new File([b],`crediti-${String(i+1).padStart(2,'0')}.jpg`,{type:b.type?.startsWith('image/')?b.type:'image/jpeg'})}
 async function prepararArquivos(){if(!state)return;const marca=state;marca.filesReady=false;try{const sel=marca.fotos.filter(x=>x.on);marca.files=await Promise.all(sel.map((x,i)=>arquivo(x.url,i)));if(state===marca)marca.filesReady=true}catch(_){if(state===marca){marca.files=[];marca.filesReady=false}}}
 async function abrir(id){state={v:{id,modelo:'Veículo'},fotos:[],files:[],filesReady:false,erro:'Carregando…'};render();try{const v=await buscar(id),fs=[...(v.fotos_veiculo||[])].sort((a,b)=>(a.ordem||99)-(b.ordem||99)).slice(0,MAX).map(x=>({url:x.url_foto,on:true}));state={v,fotos:fs,files:[],filesReady:false,erro:fs.length?'Preparando fotos…':'Este veículo ainda não possui fotos.'};render();await prepararArquivos();if(state){state.erro=state.filesReady?'':'Não foi possível preparar as fotos.';render()}}catch(_){state.erro='Não foi possível carregar o veículo. Tente novamente.';render()}}
 function compartilhar(dest){if(busy||!state)return;const files=state.files||[];if(!state.filesReady||!files.length){state.erro='As fotos ainda estão sendo preparadas. Aguarde um instante e toque novamente.';render();return}if(!navigator.share||(navigator.canShare&&!navigator.canShare({files}))){state.erro='Este navegador não liberou o compartilhamento das fotos.';render();return}busy=true;const instagram=dest==='post'||dest==='stories'||dest==='direct';const dados={title:nome(state.v),files};if(!instagram&&dest!=='mais'){dados.text=texto(state.v);dados.url=url(state.v)}const p=navigator.share(dados);Promise.resolve(p).then(()=>fechar()).catch(e=>{busy=false;if(e?.name!=='AbortError'){state.erro='O iPhone não abriu o destino. Toque em Mais opções e escolha Instagram ou WhatsApp.';render()}})}
 document.addEventListener('click',e=>{const b=e.target.closest?.('button');if(!b||!b.textContent?.includes('Compartilhar com cliente'))return;const a=b.closest('article[id^="veiculo-"]');if(!a)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();abrir(a.id.replace('veiculo-',''))},true);window.addEventListener('pageshow',()=>{if(!state)lock(false)});
})();